<img src="images/keepcoding.png" width=200 align="left">

# Sistemas de ecuaciones lineales

<img src="images/ecuaciones.jpg" width=400 align="center">

Hemos ido viendo algunos sistemas de ecuaciones en los temas anteriores, ahora vamos a juntar todo lo que sabemos. 


# 1. Definición 

Un sistema de $m$ ecuaciones lineales con $n$ incógnitas es un conjunto de ecuaciones lineales que se puede escribir de la siguiente forma:<br><br>
  

<center>$a_{11}\cdot x_1+a_{12}\cdot x_2+...+a_{1n}\cdot x_n=b_1$<br></center>
<center>$a_{21}\cdot x_1+a_{22}\cdot x_2+...+a_{1n}\cdot x_n=b_2$<br></center>
<center>...</center>
<center>$a_{m1}\cdot x_1+a_{m2}\cdot x_2+...+a_{mn}\cdot x_n=b_m$<br></center>  

Como el sistema es **lineal**, es decir, es una suma en la que cada sumando es una incógnita multiplicada por un escalar, podemos aplicar el producto de matrices y escribirlo de la siguiente forma:<br><br>

<center>
$\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n}\\
   a_{21} & a_{22} & ... & a_{2n}\\
   ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn}\\
  \end{array} } \right)\left( {\begin{array}{cc}
   x_{1}\\
   x_{2}\\
   ... \\
   x_{n}\\
  \end{array} } \right) = \left( {\begin{array}{cc}
   b_{11}\\
   b_{21}\\
   ... \\
   b_{m1}\\
  \end{array} } \right)$ 
</center><br><br>

Donde se llama **matriz de coeficientes** a:<br>

<center>$A=\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n}\\
   a_{21} & a_{22} & ... & a_{2n}\\
   ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn}\\
  \end{array} } \right)$ 
</center><br><br>
  
Y **matriz ampliada** a la matriz que incluye también el término independiente (es decir, el que no está multiplicando a ninguna incógnita):<br><br>

<center>$A^{*}=\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n} & b_{1n}\\
   a_{21} & a_{22} & ... & a_{2n} & b_{2n}\\
   ... & ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn} & b_{mn}\\
  \end{array} } \right)$ 
</center><br><br>

Usando la matriz de coeficientes, podemos reescribir el sistema de forma más compacta:
<center>$Ax = B$</center>

Donde $A$ es una matriz de $mxn$, $x$ y $B$ son dos vectores columna de longitud $n$. 


## 2. Resolución del sistema

Para poder resolver esta ecuación $Ax = B$ debemos despejar $x$, para ello tenemos en cuenta las propiedades de las matrices que hemos visto:<br>

<center>$Ax = B$</center><br>
<center>$A^{-1}Ax = A^{-1}B$</center><br>
<center>$Ix = A^{-1}B$</center><br>
<center>$x = A^{-1}B$</center><br>

Sin embargo, no todos los sistemas de ecuaciones de este tipo tienen solución, y algunos incluso tienen infinitas soluciones.

Del desarrollo anterior, podemos imaginar que si la matriz A es **singular**, no podremos invertirla y por tanto no llegaremos a la solución para x. 

En general, nos podemos encontrar tres situaciones distintas. Nos puede ayudar pensar en un sistema de dos ecuaciones con dos incógnitas, que podemos ver como dos rectas en el plano. Resolver el sistema equivale a ver los puntos de corte entre estas dos rectas.

<img src="images/sistemas-ec.png" align="center">



### 2.1 Sistema compatible determinado

Este es el caso en el que la matriz es invertible, por lo tanto podemos identificarlo con $\det(A)\neq 0$.

<img src="images/compatible.png" align="center">

Como ejemplo, resolvemos el siguiente sistema de ecuaciones:

2x + 3y - z = 8 \
4x - y + 2z = -3 \
x + 2y - 3z = 15

In [1]:
import numpy as np
A = np.array([[2, 3, -1], [4, -1, 2], [1, 2, -3]])
A

array([[ 2,  3, -1],
       [ 4, -1,  2],
       [ 1,  2, -3]])

In [2]:
B = np.array([8, -3, 15])
B

array([ 8, -3, 15])

In [3]:
# Comprobamos el determinante 
np.linalg.det(A)

31.0

In [4]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.03225806,  0.22580645,  0.16129032],
       [ 0.4516129 , -0.16129032, -0.25806452],
       [ 0.29032258, -0.03225806, -0.4516129 ]])

In [6]:
# Vector solución
X = np.dot(A_inv, B)
# A_inv.dot(B)
# A_inv @ B
print(X)

[ 1.48387097  0.22580645 -4.35483871]


También podemos calcularlo directamente con `solve`:

In [7]:
X = np.linalg.solve(A, B)
print(X)

[ 1.48387097  0.22580645 -4.35483871]


En caso de que B=0, es decir, ninguna de las ecuaciones tenga término independiente, la solución del sistema compatible determinado va a ser el punto 0. Para nuestro caso particular en dos dimensiones, si las dos rectas pasan por el 0 y la solución es única, necesariamente tiene que coincidir con el 0.

<img src="images/compatible-b0.png" align="center">

Vamos a probar a resolver este otro sistema:
 
2x - y - z = 0 \
4x - 2y + 2z = 0 \
-z + x= 0 

In [9]:
A = np.array([[2, -1, -1], [4, -2, 2], [1, 0, -1]])
B = np.array([0, 0, 0])

In [10]:
print(A)
print(B)

[[ 2 -1 -1]
 [ 4 -2  2]
 [ 1  0 -1]]
[0 0 0]


In [11]:
X = np.linalg.solve(A,B)
X

array([ 0.,  0., -0.])

In [ ]:
# multiplicar por 0 siempre nos va a dar 0

### 2.2 Sistema compatible indeterminado

Estamos ante otro tipo de sistema compatible, es decir, con solución. Sin embargo, en este caso nos encontramos con que hay más de una solución. Si hay más de una solución en el sistema lineal es porque las ecuaciones con coincidentes, por lo que tenemos que tener infinitas soluciones.

Ya sabemos por el apartado anterior que si la matriz es invertible encontramos una única solución, por lo que ahora estamos en el caso $\det(A) = 0$. Sin embargo, dentro de esta condición también se encuentran los sistemas sin solución, y aprenderemos a distinguirlos.

Imaginemos de nuevo nuestras dos rectas en el plano. Que no haya soluciones quiere decir que las rectas son paralelas (misma pendiente, distinto punto de corte con el eje y) y que haya infinitas soluciones implica que las rectas son coincidentes (misma pendiente y mismo punto de corte con el eje y).

<img src="images/compatible-indet.png" align="center">

No vamos a ver en detalle cómo ver si se trata de un caso u otro, pero a grandes rasgos:

- Podemos aplicar sumas y productos por un escalar a las filas de la matriz sin modificar la solución.
- Aplicamos estas operaciones entre filas y llegamos a un sistema equivalente que o bien tiene una fila de ceros (sistema compatible) o bien tiene una fila del tipo a=0 con a!=0, es decir, una contradicción.

Es decir, en este caso compatible indeterminado, necesitamos que no solo la matriz A tenga filas linealmente dependientes, sino también la matriz ampliada con el vector B. Podríamos decir que "nos sobran ecuaciones" porque alguna de ellas nos da información repetida que ya teníamos con las otras.

Probamos con el siguiente sistema de ecuaciones:

<center>
\begin{cases} x + 2y -z = 1 \\ -x + y + 2z = 3 \\ x + 5y = 5\end{cases}
</center>

Que en forma matricial tiene este aspecto:

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1\\
   -1 & 1 & 2\\
   1 & 5 & 0\\
  \end{array} } \right)\left( {\begin{array}{cc}
   x\\
   y\\
   z\\
  \end{array} } \right) = \left( {\begin{array}{cc}
   1\\
   3\\
   5\\
  \end{array} } \right)$ </center>

In [13]:
import sympy
A = np.array([[1, 2, -1],
             [-1, 1, 2],
             [1, 5, 0]])

B = np.array([1, 3, 5]) #.reshape(3, 1)

In [14]:
np.linalg.det(A)

0.0

In [15]:
# La matriz sigue siendo singular !!
np.linalg.inv(A)

LinAlgError: Singular matrix

In [3]:
import sympy

x = sympy.Symbol('x')
y = sympy.Symbol('y')
z = sympy.Symbol('z')

fun1 = x + 2*y -z -1
fun2 = -x + y + 2*z - 3
fun3 = x + 5*y - 5

In [ ]:
!pip install sympy

In [4]:
solucion = sympy.solvers.solve([fun1, fun2, fun3], [x, y, z])
solucion

{x: 5*z/3 - 5/3, y: 4/3 - z/3}

In [5]:
type(solucion)

dict

In [6]:
solucion[x]

5*z/3 - 5/3

In [7]:
solucion[y]

4/3 - z/3

Nos puede llamar la atención que la solución depende de z, pero esto es consecuencia de que el sistema tenga infinitas ecuaciones. Podemos dar cualquier valor real a z y obtener una solución al problema.

In [12]:
z = 3.45
print(f'Soluciones para z = {z}')
print(f'x = {solucion[x].evalf(subs={Symbol("z"):z})}')
print(f'y = {solucion[y].evalf(subs={Symbol("z"):z})}')

Soluciones para z = 3.45
x = 4.08333333333333
y = 0.183333333333333


### 2.3 Sistema incompatible

El caso que nos faltaba lo tenemos casi estudiado del apartado anterior. En este caso $\det(A) = 0$ y además sabemos que las ecuaciones no van a ser equivalentes sino que van a diferir en su término independiente. En dos dimensiones, nuestras dos rectas van a ser paralelas pero no coincidentes:

<img src="images/incompatible.png" align="center">

El término independiente es el punto de corte de cada recta con el eje y, por lo que a simple vista ya vemos que $B \neq 0$ en este caso, puesto que de lo contrario el vector 0 tendría que ser solución, y ya no sería un sistema incompatible.

Vemos un ejemplo:


<center>
\begin{cases} x + 2y -z = 1 \\ -x + y + 2z = 3 \\ x + 5y = 0\end{cases}
</center>

En forma matricial:

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1\\
   -1 & 1 & 2\\
   1 & 5 & 0\\
  \end{array} } \right)\left( {\begin{array}{cc}
   x\\
   y\\
   z\\
  \end{array} } \right) = \left( {\begin{array}{cc}
   1\\
   3\\
   0\\
  \end{array} } \right)$ </center>
 


In [15]:
import numpy as np
A = np.array([[1, 2, -1],
            [-1, 1, 2],
            [1, 5, 0]])

B = np.array([1, 3, 0])
print(A)
print(B)

[[ 1  2 -1]
 [-1  1  2]
 [ 1  5  0]]
[1 3 0]


In [16]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [17]:
import sympy

x = sympy.Symbol('x')
y = sympy.Symbol('y')
z = sympy.Symbol('z')

fun1 = x + 2*y -z -1
fun2 = -x + y + 2*z - 3
fun3 = x + 5*y 

sympy.solvers.solve([fun1, fun2, fun3], [x, y, z])

[]

## 3. Ejercicio: pleantear un sistema de ecuaciones

Imagina que tienes una tienda que vende dos tipos de productos: camisetas y pantalones. Sabes que por cada camiseta vendida, ganas 10 euros, y por cada pantalón vendido, ganas 20 euros.

Si en un día vendes un total de 30 prendas y ganas 450  euros en total, puedes plantear un sistema de ecuaciones para encontrar cuántas camisetas y cuántos pantalones vendiste ese día.

Llamamos: 
x a la cantidad de camisetas vendidas y 
y a la cantidad de pantalones vendidos. 

Resolver este sistema de ecuaciones lineales nos permitirá determinar cuántas camisetas y cuántos pantalones se vendieron ese día para alcanzar esa cantidad de prendas vendidas y ganancias totales.

In [22]:
x = Symbol('x')
y = Symbol('y')

fun1 = x+y-30 # x + y = 30
fun2 = 10*x + 20*y - 450 # 10x + 20y = 450

sol= solve([fun2,fun1],[x,y])
print(sol[x])
print(sol[y])

15
15


In [21]:
A = np.array([[1, 1], [10, 20]])
B= np.array([30, 450])

X = np.linalg.solve(A, B)
print(X[0])
print(X[1])

15.0
15.0
