<img src="images/keepcoding.png" width=200 align="left">

# Tensores

## 1. Definición

Hay diferentes definiciones dependiendo del ámbito (física, matemáticas, informática...). Para nosotros, va a ser una generalización de escalares, vectores y matrices a un número arbitrario de dimensiones (o ejes), y los vamos a usar para almacenar datos multidimensionales.

Por tanto, un vector y una matriz **también son tensores**, de dimensión 1 y 2 respectivamente. En dimensión 1 necesitábamos un subíndice para definir el vector. En dimensión 2, dos subíndices, y ahora podremos necesitar un número arbitrario de ellos.

<img src="images/tensor.png" width=70%/>


**¿Para qué vamos a usarlos?** En machine learning y deep learning los usaremos para almacenar datos y operar con ellos rápida y fácilmente. Por ejemplo, almacenar un array de imágenes para un clasificador con Deep Learning o la relación entre varias palabras en un modelo de procesamiento de lenguaje natural. Podemos usar Python con numpy, tensorflow, keras...

<img src="images/tensor-cubo.jpeg" width=30%/>


## 2. Representación de tensores

Usando como ejemplo un tensor en tres dimensiones, ya hemos visto que necesitaríamos tres índices para almacenar los datos. Podemos verlo como un conjunto de matrices, una a continuación de la otra.

$ T =
  \left( {\begin{array}{cc}
   t_{111}, t_{121}, t_{131} \\  
   t_{211}, t_{221}, t_{231} \\  
   t_{311}, t_{321}, t_{331} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   t_{112}, t_{122}, t_{132} \\  
   t_{212}, t_{222}, t_{232} \\  
   t_{312}, t_{322}, t_{332} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   t_{113}, t_{123}, t_{133} \\  
   t_{213}, t_{223}, t_{233} \\  
   t_{313}, t_{323}, t_{333} \\  
  \end{array} } \right)
  $

In [2]:
import numpy as np
T = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
             [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
             [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(T)
print(T.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
(3, 3, 3)


Que la dimensión sea (3, 3, 3) quiere decir que tenemos tres filas y tres columnas en cada matriz, y además tres matrices una detrás de la otra. Si lo vemos como un paralelepípedo, será un cubo de tamaño 3.

In [3]:
T[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
T[0][0]

array([1, 2, 3])

In [5]:
T[0][0][0]

1

In [6]:
T[0][0][0][0]

IndexError: invalid index to scalar variable.

In [31]:
T[0,0,0] = 200

In [32]:
T[0:3:2,]

array([[[200,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [9]:
T

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

## 3. Operaciones elementales

### 3.1 Suma de tensores

La suma (y la resta de tensores) se hace elemento a elemento, igual que lo hacíamos con las matrices. Aplican de nuevo la **asociatividad**, **conmutatividad**, **existencia de elemento neutro** y **existencia de inverso**.

In [3]:
import numpy as np
A = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
             [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
             [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [5]:
B = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
             [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
             [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [6]:
A + B

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [7]:
A - B

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

¿Qué pasa si no tienen el mismo tamaño?

In [8]:
B = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
             [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(B.shape)

(2, 3, 3)


In [9]:
A + B

ValueError: operands could not be broadcast together with shapes (3,3,3) (2,3,3) 

### 3.2 Producto de un tensor por un escalar 

El producto de un tensor por un escalar también tiene como resultado un tensor donde cada elemento está multiplicado por el escalar.

In [10]:
D = np.ones((3,3,3))
print(D)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [11]:
2.78*D

array([[[2.78, 2.78, 2.78],
        [2.78, 2.78, 2.78],
        [2.78, 2.78, 2.78]],

       [[2.78, 2.78, 2.78],
        [2.78, 2.78, 2.78],
        [2.78, 2.78, 2.78]],

       [[2.78, 2.78, 2.78],
        [2.78, 2.78, 2.78],
        [2.78, 2.78, 2.78]]])

In [12]:
F = 2.78*D - 0.23*A

In [13]:
F

array([[[2.55, 2.32, 2.09],
        [1.86, 1.63, 1.4 ],
        [1.17, 0.94, 0.71]],

       [[2.55, 2.32, 2.09],
        [1.86, 1.63, 1.4 ],
        [1.17, 0.94, 0.71]],

       [[2.55, 2.32, 2.09],
        [1.86, 1.63, 1.4 ],
        [1.17, 0.94, 0.71]]])

**Recordatorio**: Para todas las operaciones elemento a elemento, necesitamos que la dimensión sea la misma.

## 4. Ejemplo: uso de un tensor para almacenar una imagen RGB

In [33]:
!pip install image_to_numpy

  Using cached image_to_numpy-1.0.0-py3-none-any.whl


In [34]:
import image_to_numpy
import matplotlib.pyplot as plt

<img src="images/tensor.png" width=70%/>

In [36]:
img = image_to_numpy.load_image_file('images/tensor.png', mode="RGB")
img.shape

(283, 800, 3)

In [37]:
img[20:40, 200:249, 0]

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 25